export {
  FACTION_IDS,
  FACTION_ID_LIST,
  FACTIONS,
  DEFAULT_PLAYER_FACTION_ID,
  DEFAULT_REPUTATION,
  MIN_REPUTATION,
  MAX_REPUTATION,
  RELATIONSHIP_MATRIX,
  adjustReputation,
  clampReputation,
  createDefaultReputation,
  resolveStance,
  setReputation,
  type FactionDefinition,
  type FactionId,
  type FactionKey,
  type Reputation,
  type ReputationMap,
  type Stance,
} from './factions'
